### ISSUE TITLE
Flow File fails to import after migration

### ISSUE THREAD

**Issue by Intelligent-Advisor** [oracle-samples/ia-tools-samples#10]
Hi

I used the migrator to migrate the Emergency Response example project. The outcome was positive

<img width="865" alt="Outcome migrate OIA 24A" src="https://github.com/oracle-samples/ia-tools-samples/assets/136969466/3c2f5c43-e464-4be5-97a7-f8506a061325">

However the import failed in the Hub. Is there a specific version of the Hub required for this to work (using 24A .522 7 Feb)

<img width="248" alt="Error Migrate Import Flow" src="https://github.com/oracle-samples/ia-tools-samples/assets/136969466/0bdb5ea1-9fb1-49a0-8e4b-11f3c14b0083">

The Hub has the flow scheme I used for the migration available and I have necessary workspace permissions.

Thanks for your suggestions! I attach the JSON migrated flow file.
[demofinishedflow.json](https://github.com/oracle-samples/ia-tools-samples/files/14450790/demofinishedflow.json)

**Comment by cflemmingoracle** [comment]
Hi, thanks for reporting this. We weren't able to reproduce this error. Please re-test with the latest versions of Policy Modeling, the IA Hub, and the migrator tool.

**Comment by Intelligent-Advisor** [comment]
Hello. 

Here are the steps I performed to test.

1. In the Hub (version 12.2.34.537 - Thursday, 07 March 2024 09:31) download OPM
2. In the Hub, create a Flow Scheme for Web-based flows. 
3. Commit the Flow Scheme as-is.
4. Download the flow scheme file _scheme.json_  and place it in c:\temp
5. In OPM, open the HealthyEating project (example project). Ensure the files are in c:\temp\HealthyEating
6. Download migrator tool
7. Move the example settings file (Example-Settings.json) to the c:\temp folder
8. Run the migrator with npx ts-node src/main C:\temp\HealthyEating  --scheme "C:\temp\scheme.json"  --settings "c:\temp\Example-Settings.json" --outproject C:\temp\demofinishedflow2.json

Output is as follows, seemingly no major issues :

```
C:\migrator\migrator>npx ts-node src/main C:\temp\HealthyEating  --scheme "C:\temp\scheme.json"  --settings "c:\temp\Example-Settings.json" --outproject C:\temp\demofinishedflow2.json
Converting Food Pyramid Rules.xlsx
Warning: Unnamed conclusion heading skipped at C2, "Fruit"
Warning: Unnamed conclusion heading skipped at C2, "Veg"
Warning: Unnamed conclusion heading skipped at C2, "Grains"
Warning: Unnamed conclusion heading skipped at C2, "Meat"
Warning: Unnamed conclusion heading skipped at C2, "Dairy"
Warning: Unnamed conclusion heading skipped at C2, "Sweets"
Converting Source Rules.docx
Converting System Rules.docx
Warning: Event rule will be converted to a boolean rule: "error("Please enter details for at least one child")"
Converting screen 'Welcome'
Converting screen 'Family Details'
Converting screen 'Food Consumed'
Converting screen 'Assessor Details'
Warning: No conversion available for control type "SignatureControl". This control has been omitted from the converted screen.
Converting screen 'Thank You'
Warning: No conversion available for control type "DocumentControl". This control has been omitted from the converted screen.
Warning: No conversion available for control type "DocumentControl". This control has been omitted from the converted screen.
Warning: No conversion available for control type "DocumentControl". This control has been omitted from the converted screen.
Warning: No conversion available for control type "DocumentControl". This control has been omitted from the converted screen.
Warning: No conversion available for control type "DocumentControl". This control has been omitted from the converted screen.
Done.
```
In the Hub, proceed to Projects tab and Actions menu, and click Import
Verify that the scheme used in the migration is present in the Hub
Select the C:\temp\demofinishedflow2.json file generated by the migrator
Observe the error message 
![image](https://github.com/oracle-samples/ia-tools-samples/assets/136969466/9c98f43d-f100-4693-83e9-8c49893729dd)

Attached are the output of the migrator, the flow scheme, the example settings and the config file.

R
[demofinishedflow2.json](https://github.com/oracle-samples/ia-tools-samples/files/14774487/demofinishedflow2.json)
[scheme.json](https://github.com/oracle-samples/ia-tools-samples/files/14774488/scheme.json)
[Example-Settings.json](https://github.com/oracle-samples/ia-tools-samples/files/14774489/Example-Settings.json)
[settings.json](https://github.com/oracle-samples/ia-tools-samples/files/14774490/settings.json)

**Comment by cflemmingoracle** [comment]
Thanks, those additional steps allowed us to reproduce the issue. We have merged in a fix.
