### ISSUE TITLE
currentDate

### ISSUE THREAD

**Issue by Intelligent-Advisor** [oracle-samples/ia-tools-samples#3]
Hi. 
Attempting to migrate a simple example - EnergySaver from OPM, with no specific settings, when the flow is generated it contains a schemeDataMapping called  $currentDate. I cannot see the current date used anywhere in the OPM rules.  

I would expect this to be present if the current date was in the rules, as per the documentation of the migrator. Why does it show in this particular case?

![image](https://github.com/oracle-samples/ia-tools-samples/assets/136969466/87464b26-d82a-472b-8054-45e2c7296233)

Thanks for all your fantastic work!

**Comment by bradtuckett** [comment]
All flow projects using the default template will automatically create and maps a field called "the current date" from the global input data - as shown in the "[Add or edit input data in a flow scheme](https://documentation.custhelp.com/euf/assets/devdocs/unversioned/IntelligentAdvisor/en/Content/Guides/Use_Intelligent_Advisor/Author_flow_schemes/Add_edit_input_data_flow_scheme.htm)" topic in the documentation

**Comment by Intelligent-Advisor** [comment]
Thank you for clarifying.
