### ISSUE TITLE
Missing Fields

### ISSUE THREAD

**Issue by Intelligent-Advisor** [oracle-samples/ia-tools-samples#4]
Hi.
When migrating the example OPM project Energy Saver, several attributes (for example "the person has a washing machine") are collected on Screens and then used only to define control visibility rules. They are not used in any rule document in the project and are collected on a Screen:

![image](https://github.com/oracle-samples/ia-tools-samples/assets/136969466/1f0f2016-2cb3-4013-9faa-51415b638f34)

I assume for that reason they are not being migrated  by the migrator tool, and have to be recreated in the Flow? 

Thanks for clarifying.

**Comment by bradtuckett** [comment]
Yes.  The migrator only migrates rules, not screens.

**Comment by bradtuckett** [comment]
Screens are now be migrated for flows, so that should resolve this issue.
