### ISSUE TITLE
Example-Settings.json

### ISSUE THREAD

**Issue by Intelligent-Advisor** [oracle-samples/ia-tools-samples#9]
Hello

The Example-Settings.json appears to not work in the current version of the tool when migrating an OPM Interview project to a Flow. It appears that a reference for a basic text control is missing. The error when using the example file is

`Error in settings: "$settings.flowControls.input.text.text" should be a string`

Looking at the sample file the text input section looks like this

```
 "text":
            {
		"text-area": "text-textarea",
                "password": "text-password",
                "masked": "text-masked"
            },
```

Adding a basic map to a text control removes the error :

```
 "text":
            {
                 "text": "text",
		 "text-area": "text-textarea",
                "password": "text-password",
                "masked": "text-masked"
            },
```

Not sure if that is all that is required, but wanted to flag the error anyway. Thanks!

**Comment by bradtuckett** [comment]
We will make mapping to a text control optional.  Tracking as OZ-20374
